create database school_library
use school_library
CREATE TABLE UYELER(
	UYE_NO INT IDENTITY(1,1),
	UYE_ADI VARCHAR(20),
	UYE_SOYADI VARCHAR(20),
	CINSIYET VARCHAR(5),
	TELEFON VARCHAR(15),
	EPOSTA VARCHAR(40),
	ADRES_NO INT,
	PRIMARY KEY("UYE_NO")
);

ALTER TABLE UYELER ADD CONSTRAINT "ADRESLER_UYELER" 
FOREIGN KEY (ADRES_NO) REFERENCES ADRESLER(ADRES_NO);

CREATE TABLE ADRESLER(
	ADRES_NO INT IDENTITY(1,1),
	CADDE VARCHAR(20),
	MAHALLE VARCHAR(20),
	BINA_NO VARCHAR(20),
	SEHIR VARCHAR(20),
	POSTA_KODU INT, 
	ULKE VARCHAR(20),
	PRIMARY KEY ("ADRES_NO")
);


CREATE TABLE EMANET(
	EMANET_NO INT IDENTITY(1,1),
	ISBN VARCHAR(20) NOT NULL,
	UYE_NO INT NOT NULL,
	KUTUPHANE_NO INT NOT NULL,
	EMANET_TARIHI DATETIME,
	TESLIM_TARIHI DATETIME,
	PRIMARY KEY ("EMANET_NO")
);

CREATE TABLE KITAPLAR(
	ISBN VARCHAR(20),
	KITAP_ADI VARCHAR(20),
	YAYIN_TARIHI VARCHAR(20),
	S_SAYISI INT,
	PRIMARY KEY ("ISBN")
);

CREATE TABLE YAZARLAR(
	YAZAR_NO INT IDENTITY(1,1),
	YAZAR_ADI VARCHAR(20),
	YAZAR_SOYADI VARCHAR(20),
	PRIMARY KEY ("YAZAR_NO")
);

CREATE TABLE KATEGORILER(
	KATEGORI_NO INT IDENTITY(1,1),
	KATEGORI_ADI VARCHAR(20),
	PRIMARY KEY ("KATEGORI_NO")
);

CREATE TABLE KUTUPHANE(
	KUTUPHANE_NO INT IDENTITY(1,1),
	KUTUPHANE_ADI VARCHAR(20),
	ACIKLAMA VARCHAR(20),
	ADRES_NO INT,
	PRIMARY KEY ("KUTUPHANE_NO")
);

CREATE TABLE KITAP_KUTUPHANE(
	KUTUPHANE_NO INT NOT NULL,
	ISBN VARCHAR(20) NOT NULL,
	MIKTAR INT,
	CONSTRAINT "KITAP_KUTUPHANE_PK" PRIMARY KEY ("KUTUPHANE_NO", "ISBN"),
	CONSTRAINT "KITAP_KUTUPHANE_FK" FOREIGN KEY ("KUTUPHANE_NO") REFERENCES KATEGORILER(KATEGORI_NO)

);

ALTER TABLE KITAP_KUTUPHANE ADD CONSTRAINT "KITAP_KUTUPHANE_KITAPLAR_FK" FOREIGN KEY ("ISBN") REFERENCES KITAPLAR(ISBN);


CREATE TABLE KITAP_KATEGORI(
	ISBN VARCHAR(20) NOT NULL,
	KATEGORI_NO INT NOT NULL,
	CONSTRAINT "KITAP_KATEGORI_PK" PRIMARY KEY ("KATEGORI_NO", "ISBN")
);

CREATE TABLE KITAP_YAZAR(
	ISBN VARCHAR(20) NOT NULL,
	YAZAR_NO INT NOT NULL,
	CONSTRAINT "KITAP_YAZAR_PK" PRIMARY KEY ("YAZAR_NO", "ISBN")
);


---KUTUPHANE
USE OKUL_KUTUPHANESI;
ALTER TABLE KUTUPHANE ADD CONSTRAINT "ADRESLER_KUTUPHANE" 
FOREIGN KEY (ADRES_NO) REFERENCES ADRESLER(ADRES_NO)
ON DELETE SET NULL
ON UPDATE CASCADE;

--- EMANET

USE OKUL_KUTUPHANESI;
ALTER TABLE EMANET ADD CONSTRAINT "UYELER_EMANET" 
FOREIGN KEY (UYE_NO) REFERENCES UYELER(UYE_NO);

USE OKUL_KUTUPHANESI;
ALTER TABLE EMANET ADD CONSTRAINT "EMANET_KITAPLAR" 
FOREIGN KEY (ISBN) REFERENCES KITAPLAR(ISBN);

USE OKUL_KUTUPHANESI;
ALTER TABLE EMANET ADD CONSTRAINT "KUTUPHANE_EMANET" 
FOREIGN KEY (KUTUPHANE_NO) REFERENCES KUTUPHANE(KUTUPHANE_NO);

---KITAP_KATEGORI
USE OKUL_KUTUPHANESI;
ALTER TABLE KITAP_KATEGORI ADD CONSTRAINT KATEGORILER_KITAP_KATEGORI
FOREIGN KEY (KATEGORI_NO) REFERENCES KATEGORILER(KATEGORI_NO);

USE OKUL_KUTUPHANESI;
ALTER TABLE KITAP_KATEGORI ADD CONSTRAINT KITAPLAR_KITAP_KATEGORI
FOREIGN KEY (ISBN) REFERENCES KITAPLAR(ISBN);

---KITAP_YAZAR
USE OKUL_KUTUPHANESI;
ALTER TABLE KITAP_YAZAR ADD CONSTRAINT YAZARLAR_KITAP_YAZAR
FOREIGN KEY (YAZAR_NO) REFERENCES YAZARLAR(YAZAR_NO);

USE OKUL_KUTUPHANESI;
ALTER TABLE KITAP_YAZAR ADD CONSTRAINT KITAPLAR_KITAP_YAZAR
FOREIGN KEY (ISBN) REFERENCES KITAPLAR(ISBN);

---KITAP_KUTUPHANE
USE OKUL_KUTUPHANESI;
ALTER TABLE KITAP_KUTUPHANE ADD CONSTRAINT KUTUPHANE_KITAP_KUTUPHANE
FOREIGN KEY (KUTUPHANE_NO) REFERENCES KUTUPHANE(KUTUPHANE_NO);

USE OKUL_KUTUPHANESI;
ALTER TABLE KITAP_KUTUPHANE ADD CONSTRAINT KITAPLAR_KITAP_KUTUPHANE
FOREIGN KEY (ISBN) REFERENCES KITAPLAR(ISBN);

SELECT * FROM UYELER;
SELECT * FROM ADRESLER;
INSERT INTO UYELER VALUES('ELÝF','civelekoðlu','k','12345','fnya@sdfsdfsdf',1)
INSERT INTO UYELER VALUES('ASDF','SADASDA','k','12345','fnya@sdfsdfsdf',2)
INSERT INTO UYELER VALUES('TYUTYUYF','SDFDSF','k','12345','fnya@sdfsdfsdf',3)
INSERT INTO ADRESLER VALUES('MEVLANA','15 TEMMUZ','TBMYO','KAYSERÝ',3800,'TÜRKÝYE')
INSERT INTO ADRESLER VALUES('MEVLANA','15 TEMMUZ','BURSA ULUDAÐ','BURSA',1600,'TÜRKÝYE')
UPDATE UYELER SET UYE_ADI=' Elif '
WHERE UYE_no= 1

DELETE FROM UYELER WHERE UYE_NO=6

SELECT * FROM YAZARLAR;
INSERT INTO YAZARLAR VALUES('DSNKGLSD','MBVNÖVC')
INSERT INTO YAZARLAR VALUES('UYTUTY','POIPIOPI')
SELECT * FROM KATEGORILER;
INSERT INTO KATEGORILER VALUES('ASDASDASD')
INSERT INTO KATEGORILER VALUES('ERITOERUTOIE')
SELECT * FROM KITAPLAR;
INSERT INTO KITAPLAR VALUES('ASDASDASD','OYUN','ON MART',60)
INSERT INTO KITAPLAR VALUES('RTJRETERTOE','MACERA','DOKUZ MART',90)
SELECT * FROM KITAP_KATEGORI;
INSERT INTO KITAP_KATEGORI VALUES('SASAD',5464)
INSERT INTO KITAP_KATEGORI VALUES('GHJGHJG',56756)
SELECT * FROM KUTUPHANE;
INSERT INTO KUTUPHANE VALUES('BDFJKGBDFJK','GMLKBHFMGHLKFMG',5656)
INSERT INTO KUTUPHANE VALUES('BVB NMB CÖMVB','HJÖÞLKJHÖ',9896)
SELECT * FROM KITAP_YAZAR;
INSERT INTO KITAP_YAZAR VALUES('BNMBN',415643)
INSERT INTO KITAP_YAZAR VALUES('UIPOUIÐ',156486)
SELECT * FROM EMANET;
INSERT INTO EMANET VALUES('BDFJKGBDFJK',456546,978978,20.456,20.01)
INSERT INTO EMANET VALUES('BCVMLÞDFK',564658978,7564563,56.21,24.05)